### ISSUE TITLE
opi files appear modified after cloning on Windows

### ISSUE THREAD

**Issue by kmpeters** [epics-modules/softGlue#2]
I'm using the following version of git on Window 7 (64-bit):

```
$ git --version
git version 2.9.3.windows.1
```

I clone softGlue using the git bash shell:

```
$ git clone https://github.com/epics-modules/softGlue.git
Cloning into 'softGlue'...
remote: Counting objects: 4445, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 4445 (delta 0), reused 0 (delta 0), pack-reused 4440
Receiving objects: 100% (4445/4445), 8.15 MiB | 4.92 MiB/s, done.
Resolving deltas: 100% (3317/3317), done.
Checking connectivity... done.
```

And then immediately do a git status, which shows all of the opi files as being modified:

```
$ cd softGlue
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   softGlueApp/op/opi/softGlue4DEMUX4.opi
        modified:   softGlueApp/op/opi/softGlueAll.opi
        modified:   softGlueApp/op/opi/softGlueAllButIO.opi
        modified:   softGlueApp/op/opi/softGlueAllButIO_label.opi
        modified:   softGlueApp/op/opi/softGlueAll_label.opi
        modified:   softGlueApp/op/opi/softGlueAll_octupole.opi
        modified:   softGlueApp/op/opi/softGlueConvenience.opi
        modified:   softGlueApp/op/opi/softGlueEncoder.opi
        modified:   softGlueApp/op/opi/softGlueEncoderAvg.opi
        modified:   softGlueApp/op/opi/softGlueFieldIO.opi
        modified:   softGlueApp/op/opi/softGlueFieldIO_EP202.opi
        modified:   softGlueApp/op/opi/softGlueFieldIO_Int.opi
        modified:   softGlueApp/op/opi/softGlueFieldIO_Int_EP202.opi
        modified:   softGlueApp/op/opi/softGlueFieldIO_Intxx.opi
        modified:   softGlueApp/op/opi/softGlueFieldIO_Intxx_EP202.opi
        modified:   softGlueApp/op/opi/softGlueFieldIO_Intxx_EP202_bare.opi
        modified:   softGlueApp/op/opi/softGlueFieldIO_Intxx_EP202_small_bare.opi
        modified:   softGlueApp/op/opi/softGlueFieldIO_Intxx_EP202_small_bare_label.opi
        modified:   softGlueApp/op/opi/softGlueFieldIO_Intxx_bare.opi
        modified:   softGlueApp/op/opi/softGlueFieldIO_Intxx_small_bare.opi
        modified:   softGlueApp/op/opi/softGlueFieldIO_Intxx_small_bare_label.opi
        modified:   softGlueApp/op/opi/softGlueFieldIOxx.opi
        modified:   softGlueApp/op/opi/softGlueFieldIOxx_EP202.opi
        modified:   softGlueApp/op/opi/softGlueFieldIOxx_EP202_bare.opi
        modified:   softGlueApp/op/opi/softGlueFieldIOxx_EP202_small_bare.opi
        modified:   softGlueApp/op/opi/softGlueFieldIOxx_EP202_small_bare_label.opi
        modified:   softGlueApp/op/opi/softGlueFieldIOxx_bare.opi
        modified:   softGlueApp/op/opi/softGlueFieldIOxx_small_bare.opi
        modified:   softGlueApp/op/opi/softGlueFieldIOxx_small_bare_label.opi
        modified:   softGlueApp/op/opi/softGlueHalf.opi
        modified:   softGlueApp/op/opi/softGlueMenu.opi
        modified:   softGlueApp/op/opi/softGlueOctupole.opi
        modified:   softGlueApp/op/opi/softGlueTop.opi
        modified:   softGlueApp/op/opi/softGlueVgate.opi
        modified:   softGlueApp/op/opi/softGlue_8MHZ_CK_bare.opi
        modified:   softGlueApp/op/opi/softGlue_8MHZ_CK_bare_label.opi
        modified:   softGlueApp/op/opi/softGlue_AND.opi
        modified:   softGlueApp/op/opi/softGlue_AND_bare.opi
        modified:   softGlueApp/op/opi/softGlue_AND_bare_label.opi
        modified:   softGlueApp/op/opi/softGlue_AND_debug.opi
        modified:   softGlueApp/op/opi/softGlue_BUFFER.opi
        modified:   softGlueApp/op/opi/softGlue_BUFFER_bare.opi
        modified:   softGlueApp/op/opi/softGlue_BUFFER_bare_label.opi
        modified:   softGlueApp/op/opi/softGlue_DEMUX2.opi
        modified:   softGlueApp/op/opi/softGlue_DEMUX2_bare.opi
        modified:   softGlueApp/op/opi/softGlue_DEMUX2_bare_label.opi
        modified:   softGlueApp/op/opi/softGlue_DEMUX4.opi
        modified:   softGlueApp/op/opi/softGlue_DEMUX4_bare.opi
        modified:   softGlueApp/op/opi/softGlue_DEMUX4_bare_label.opi
        modified:   softGlueApp/op/opi/softGlue_DFF.opi
        modified:   softGlueApp/op/opi/softGlue_DFF_bare.opi
        modified:   softGlueApp/op/opi/softGlue_DFF_bare_label.opi
        modified:   softGlueApp/op/opi/softGlue_DivByN.opi
        modified:   softGlueApp/op/opi/softGlue_DivByN_bare.opi
        modified:   softGlueApp/op/opi/softGlue_DivByN_bare_label.opi
        modified:   softGlueApp/op/opi/softGlue_DnCntr.opi
        modified:   softGlueApp/op/opi/softGlue_DnCntr_bare.opi
        modified:   softGlueApp/op/opi/softGlue_DnCntr_bare_label.opi
        modified:   softGlueApp/op/opi/softGlue_FieldInput.opi
        modified:   softGlueApp/op/opi/softGlue_FieldInput_bare.opi
        modified:   softGlueApp/op/opi/softGlue_FieldInput_small_bare.opi
        modified:   softGlueApp/op/opi/softGlue_FieldInput_small_bare_label.opi
        modified:   softGlueApp/op/opi/softGlue_FieldOutput.opi
        modified:   softGlueApp/op/opi/softGlue_FieldOutput_bare.opi
        modified:   softGlueApp/op/opi/softGlue_FieldOutput_small_bare.opi
        modified:   softGlueApp/op/opi/softGlue_FieldOutput_small_bare_label.opi
        modified:   softGlueApp/op/opi/softGlue_Input.opi
        modified:   softGlueApp/op/opi/softGlue_Input_small.opi
        modified:   softGlueApp/op/opi/softGlue_IntBit.opi
        modified:   softGlueApp/op/opi/softGlue_IntBit_bare.opi
        modified:   softGlueApp/op/opi/softGlue_IntBit_small_bare.opi
        modified:   softGlueApp/op/opi/softGlue_MUX2.opi
        modified:   softGlueApp/op/opi/softGlue_MUX2_bare.opi
        modified:   softGlueApp/op/opi/softGlue_MUX2_bare_label.opi
        modified:   softGlueApp/op/opi/softGlue_MUX4.opi
        modified:   softGlueApp/op/opi/softGlue_MUX4_bare.opi
        modified:   softGlueApp/op/opi/softGlue_MagCmp.opi
        modified:   softGlueApp/op/opi/softGlue_MagCmp_bare.opi
        modified:   softGlueApp/op/opi/softGlue_MagCmp_bare_label.opi
        modified:   softGlueApp/op/opi/softGlue_MagCmp_help.opi
        modified:   softGlueApp/op/opi/softGlue_OR.opi
        modified:   softGlueApp/op/opi/softGlue_OR_bare.opi
        modified:   softGlueApp/op/opi/softGlue_OR_bare_label.opi
        modified:   softGlueApp/op/opi/softGlue_Output.opi
        modified:   softGlueApp/op/opi/softGlue_OutputDebug.opi
        modified:   softGlueApp/op/opi/softGlue_Output_small.opi
        modified:   softGlueApp/op/opi/softGlue_QuadDec.opi
        modified:   softGlueApp/op/opi/softGlue_QuadDec_bare.opi
        modified:   softGlueApp/op/opi/softGlue_QuadDec_bare_label.opi
        modified:   softGlueApp/op/opi/softGlue_Shift32.opi
        modified:   softGlueApp/op/opi/softGlue_Shift32_bare.opi
        modified:   softGlueApp/op/opi/softGlue_Shift32_bare_label.opi
        modified:   softGlueApp/op/opi/softGlue_UpCntr.opi
        modified:   softGlueApp/op/opi/softGlue_UpCntr_bare.opi
        modified:   softGlueApp/op/opi/softGlue_UpCntr_bare_label.opi
        modified:   softGlueApp/op/opi/softGlue_UpDnCntr.opi
        modified:   softGlueApp/op/opi/softGlue_UpDnCntr8_bare_label.opi
        modified:   softGlueApp/op/opi/softGlue_UpDnCntr_bare.opi
        modified:   softGlueApp/op/opi/softGlue_UpDnCntr_bare_label.opi
        modified:   softGlueApp/op/opi/softGlue_XOR.opi
        modified:   softGlueApp/op/opi/softGlue_XOR_bare.opi
        modified:   softGlueApp/op/opi/softGlue_XOR_bare_label.opi
        modified:   softGlueApp/op/opi/softGlue_octupole.opi

no changes added to commit (use "git add" and/or "git commit -a")
```

A "git diff" on one of the smaller files from the bash shell shows that everything except the last line has changed:

```
diff --git a/softGlueApp/op/opi/softGlueVgate.opi b/softGlueApp/op/opi/softGlueVgate.opi
index cc40b87..da9267d 100644
--- a/softGlueApp/op/opi/softGlueVgate.opi
+++ b/softGlueApp/op/opi/softGlueVgate.opi
@@ -1,118 +1,118 @@
-<display typeId="org.csstudio.opibuilder.Display" version="1.0.0">
-  <auto_zoom_to_fit_all>false</auto_zoom_to_fit_all>
-  <macros>
-    <include_parent_macros>true</include_parent_macros>
-  </macros>
-  <wuid>-f5e3660:14f4caa0e89:-73bb</wuid>
-  <boy_version>3.2.10.20140131</boy_version>
-  <scripts />
-  <show_ruler>true</show_ruler>
-  <height>390</height>
-  <name>softGlueVgate</name>
-  <snap_to_geometry>false</snap_to_geometry>
-  <show_grid>false</show_grid>
-  <background_color>
-    <color name="Gray_2" red="218" green="218" blue="218" />
-  </background_color>
-  <foreground_color>
-    <color name="Gray_14" red="0" green="0" blue="0" />
-  </foreground_color>
-  <widget_type>Display</widget_type>
-  <show_close_button>true</show_close_button>
-  <width>485</width>
-  <rules />
-  <show_edit_range>true</show_edit_range>
-  <grid_space>5</grid_space>
-  <auto_scale_widgets>
-    <auto_scale_widgets>false</auto_scale_widgets>
-    <min_width>-1</min_width>
-    <min_height>-1</min_height>
-  </auto_scale_widgets>
-  <actions hook="false" hook_all="false" />
-  <y>276</y>
-  <x>634</x>
-  <widget typeId="org.csstudio.opibuilder.widgets.linkingContainer" version="1.0.0">
-    <macros>
-      <include_parent_macros>true</include_parent_macros>
-      <N>2</N>
-    </macros>
-    <visible>true</visible>
-    <wuid>-f5e3660:14f4caa0e89:-73ba</wuid>
-    <auto_size>false</auto_size>
-    <scripts />
-    <zoom_to_fit>true</zoom_to_fit>
-    <height>179</height>
-    <name>Linking Container</name>
-    <scale_options>
-      <width_scalable>true</width_scalable>
-      <height_scalable>true</height_scalable>
-      <keep_wh_ratio>false</keep_wh_ratio>
-    </scale_options>
-    <opi_file>softGlue_UpDnCntr_bare.opi</opi_file>
-    <foreground_color>
-      <color red="0" green="0" blue="0" />
-    </foreground_color>
-    <background_color>
-      <color red="218" green="218" blue="218" />
-    </background_color>
-    <group_name></group_name>
-    <enabled>true</enabled>
-    <widget_type>Linking Container</widget_type>
-    <font>
-      <opifont.name fontName="Sans" height="10" style="0">Default</opifont.name>
-    </font>
-    <width>467</width>
-    <border_style>3</border_style>
-    <rules />
-    <border_width>1</border_width>
-    <border_color>
-      <color red="0" green="128" blue="255" />
-    </border_color>
-    <y>203</y>
-    <actions hook="false" hook_all="false" />
-    <x>9</x>
-    <tooltip></tooltip>
-  </widget>
-  <widget typeId="org.csstudio.opibuilder.widgets.linkingContainer" version="1.0.0">
-    <macros>
-      <include_parent_macros>true</include_parent_macros>
-      <N>1</N>
-    </macros>
-    <visible>true</visible>
-    <wuid>-f5e3660:14f4caa0e89:-73b9</wuid>
-    <auto_size>false</auto_size>
-    <scripts />
-    <zoom_to_fit>true</zoom_to_fit>
-    <height>179</height>
-    <name>Linking Container</name>
-    <scale_options>
-      <width_scalable>true</width_scalable>
-      <height_scalable>true</height_scalable>
-      <keep_wh_ratio>false</keep_wh_ratio>
-    </scale_options>
-    <opi_file>softGlue_UpDnCntr_bare.opi</opi_file>
-    <foreground_color>
-      <color red="0" green="0" blue="0" />
-    </foreground_color>
-    <background_color>
-      <color red="218" green="218" blue="218" />
-    </background_color>
-    <group_name></group_name>
-    <enabled>true</enabled>
-    <widget_type>Linking Container</widget_type>
-    <font>
-      <opifont.name fontName="Sans" height="10" style="0">Default</opifont.name>
-    </font>
-    <width>467</width>
-    <border_style>3</border_style>
-    <rules />
-    <border_width>1</border_width>
-    <border_color>
-      <color red="0" green="128" blue="255" />
-    </border_color>
-    <y>14</y>
-    <actions hook="false" hook_all="false" />
-    <x>9</x>
-    <tooltip></tooltip>
-  </widget>
+<display typeId="org.csstudio.opibuilder.Display" version="1.0.0">
+  <auto_zoom_to_fit_all>false</auto_zoom_to_fit_all>
+  <macros>
+    <include_parent_macros>true</include_parent_macros>
+  </macros>
+  <wuid>-f5e3660:14f4caa0e89:-73bb</wuid>
+  <boy_version>3.2.10.20140131</boy_version>
+  <scripts />
+  <show_ruler>true</show_ruler>
+  <height>390</height>
+  <name>softGlueVgate</name>
+  <snap_to_geometry>false</snap_to_geometry>
+  <show_grid>false</show_grid>
+  <background_color>
+    <color name="Gray_2" red="218" green="218" blue="218" />
+  </background_color>
+  <foreground_color>
+    <color name="Gray_14" red="0" green="0" blue="0" />
+  </foreground_color>
+  <widget_type>Display</widget_type>
+  <show_close_button>true</show_close_button>
+  <width>485</width>
+  <rules />
+  <show_edit_range>true</show_edit_range>
+  <grid_space>5</grid_space>
+  <auto_scale_widgets>
+    <auto_scale_widgets>false</auto_scale_widgets>
+    <min_width>-1</min_width>
+    <min_height>-1</min_height>
+  </auto_scale_widgets>
+  <actions hook="false" hook_all="false" />
+  <y>276</y>
+  <x>634</x>
+  <widget typeId="org.csstudio.opibuilder.widgets.linkingContainer" version="1.0.0">
+    <macros>
+      <include_parent_macros>true</include_parent_macros>
+      <N>2</N>
+    </macros>
+    <visible>true</visible>
+    <wuid>-f5e3660:14f4caa0e89:-73ba</wuid>
+    <auto_size>false</auto_size>
+    <scripts />
+    <zoom_to_fit>true</zoom_to_fit>
+    <height>179</height>
+    <name>Linking Container</name>
+    <scale_options>
+      <width_scalable>true</width_scalable>
+      <height_scalable>true</height_scalable>
+      <keep_wh_ratio>false</keep_wh_ratio>
+    </scale_options>
+    <opi_file>softGlue_UpDnCntr_bare.opi</opi_file>
+    <foreground_color>
+      <color red="0" green="0" blue="0" />
+    </foreground_color>
+    <background_color>
+      <color red="218" green="218" blue="218" />
+    </background_color>
+    <group_name></group_name>
+    <enabled>true</enabled>
+    <widget_type>Linking Container</widget_type>
+    <font>
+      <opifont.name fontName="Sans" height="10" style="0">Default</opifont.name>
+    </font>
+    <width>467</width>
+    <border_style>3</border_style>
+    <rules />
+    <border_width>1</border_width>
+    <border_color>
+      <color red="0" green="128" blue="255" />
+    </border_color>
+    <y>203</y>
+    <actions hook="false" hook_all="false" />
+    <x>9</x>
+    <tooltip></tooltip>
+  </widget>
+  <widget typeId="org.csstudio.opibuilder.widgets.linkingContainer" version="1.0.0">
+    <macros>
+      <include_parent_macros>true</include_parent_macros>
+      <N>1</N>
+    </macros>
+    <visible>true</visible>
+    <wuid>-f5e3660:14f4caa0e89:-73b9</wuid>
+    <auto_size>false</auto_size>
+    <scripts />
+    <zoom_to_fit>true</zoom_to_fit>
+    <height>179</height>
+    <name>Linking Container</name>
+    <scale_options>
+      <width_scalable>true</width_scalable>
+      <height_scalable>true</height_scalable>
+      <keep_wh_ratio>false</keep_wh_ratio>
+    </scale_options>
+    <opi_file>softGlue_UpDnCntr_bare.opi</opi_file>
+    <foreground_color>
+      <color red="0" green="0" blue="0" />
+    </foreground_color>
+    <background_color>
+      <color red="218" green="218" blue="218" />
+    </background_color>
+    <group_name></group_name>
+    <enabled>true</enabled>
+    <widget_type>Linking Container</widget_type>
+    <font>
+      <opifont.name fontName="Sans" height="10" style="0">Default</opifont.name>
+    </font>
+    <width>467</width>
+    <border_style>3</border_style>
+    <rules />
+    <border_width>1</border_width>
+    <border_color>
+      <color red="0" green="128" blue="255" />
+    </border_color>
+    <y>14</y>
+    <actions hook="false" hook_all="false" />
+    <x>9</x>
+    <tooltip></tooltip>
+  </widget>
 </display>
\ No newline at end of file
(END)
```

However a graphical git diff from the Windows explorer shows no changes to the file.

The problem was also present with git v2.8.1.  When upgrading to the v2.9.3 I chose the option to leave line endings unchanged when checking out/in changes.

This problem isn't present on RHEL6 (git v1.7.1).

This appears to be a bug in the git bash shell, but it a major problem for anyone wanting to build softGlue on Windows, since it breaks pulling/rebasing.

**Comment by anjohnson** [comment]
Could this be fixed with a suitable entry in the .gitattributes file? My guess is that git doesn't know whether a `.opi` file is supposed to be a text file or not, so it just needs to be told how to do the right thing.

**Comment by kmpeters** [comment]
That was a great suggestion.  Adding an opi entry to the .gitattributes file does eliminate the problem:

```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   .gitattributes

no changes added to commit (use "git add" and/or "git commit -a")

$ git diff
diff --git a/.gitattributes b/.gitattributes
index 9712a09..0da026b 100644
--- a/.gitattributes
+++ b/.gitattributes
@@ -3,3 +3,4 @@
 *.sh eol=lf
 *.bat eol=crlf
 *.cmd -text
+*.opi -text
```

It still isn't obvious to me why the Windows version of git would report imaginary modifications if opi files weren't specified in the .gitattributes file.  The git-cloned files on Windows are identical to ones downloaded via Firefox using the raw-file links:

```
$ cksum *
3695449011 3862 softGlueVgate.opi-firefoxDownload
3695449011 3862 softGlueVgate.opi-windowsGitClone
$ md5sum *
baad4ccd457d4706cc1ce1d30ef4c82b *softGlueVgate.opi-firefoxDownload
baad4ccd457d4706cc1ce1d30ef4c82b *softGlueVgate.opi-windowsGitClone
$ shasum *
d2eb5d278ea83d40d93ae1041cbf8856271adeb9  softGlueVgate.opi-firefoxDownload
d2eb5d278ea83d40d93ae1041cbf8856271adeb9  softGlueVgate.opi-windowsGitClone
```

They are also identical to ones git-cloned on Linux and downloaded via wget using the raw-file links:

```
$ cksum *
3695449011 3862 softGlueVgate.opi-linuxGitClone
3695449011 3862 softGlueVgate.opi-linuxWget
$ md5sum *
baad4ccd457d4706cc1ce1d30ef4c82b  softGlueVgate.opi-linuxGitClone
baad4ccd457d4706cc1ce1d30ef4c82b  softGlueVgate.opi-linuxWget
$ shasum *
d2eb5d278ea83d40d93ae1041cbf8856271adeb9  softGlueVgate.opi-linuxGitClone
d2eb5d278ea83d40d93ae1041cbf8856271adeb9  softGlueVgate.opi-linuxWget
```

**Comment by ralphlange** [comment]
I bet the setting of the executable bit is different.
I have been fighting with this using Bazaar on a Windows host with a Linux guest VM that has the host file system mounted, and found it's more a matter of file system than OS.

**Comment by kmpeters** [comment]
I ran into this problem in the vac module.  I created an issue there with more documentation of the problem: https://github.com/epics-modules/vac/issues/3

I would create an issue for the git developers, but they apparently don't use github for issue tracking; they only accept patches via email.
